# Generated by Django 3.1.3 on 2022-03-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xhj_sccs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(db_column='url', max_length=255, verbose_name='原链接')),
                ('title', models.TextField(db_column='title', max_length=255, verbose_name='标题')),
                ('document', models.TextField(db_column='document', max_length=255, verbose_name='文章链接')),
                ('time', models.TextField(db_column='time', max_length=255, verbose_name='时间')),
            ],
            options={
                'db_table': 'xhj_sccs',
                'managed': True,
            },
        ),
    ]
