# Generated by Django 4.0.3 on 2022-03-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(db_column='link')),
                ('title', models.TextField(db_column='title')),
                ('content', models.TextField(db_column='content', null=True)),
            ],
            options={
                'db_table': 'Content',
                'managed': True,
            },
        ),
    ]
